### ISSUE TITLE
Better error handling for color and shape customization

### ISSUE THREAD

**Issue by gallettilance** [gallettilance/kviz#6]
if https://github.com/gallettilance/kviz/blob/master/kviz/dense.py#L113 fails it defaults to other values without reporting any errors. It should report errors if the regular expression fails to match

**Comment by mcxxmc** [comment]
If one value is wrong, I think there are 2 options to handle it and I myself cannot decide which one to choose:
1) report that error (e.g., print in the console) but continues with the default value; This does not bother the user to restart the program but may give an output different from expected.
2) raise an exception and halts the execution. The user will have to rerun the code with corrected inputs but next time he/she will get the desired output.
Which one do you think is better?
Or we can add another input when initializing a model (for example, silence=True to make it use the 1st option, False to the 2nd).
